### ISSUE TITLE
Build ToDo App

### ISSUE THREAD

**Issue by LevanVans** [LevanVans/todo-app-py#1]
- [ ] Setup Frontend Development environment 
- [ ]  Setup Frontend Development environment 
- [ ] Build using HTML/CSS

**Comment by LevanVans** [comment]
Done
